dist: bionic
jobs:
  include:
    - name: Chronos
      language: generic
      os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - gcc-5
          - g++-5
          - libev-dev
          - libsqlite-dev
          - libmysqlclient-dev
          - libboost-all-dev
          - libssl-dev
          - flex
          - bison
          - pkg-config
      before_script:
      - wget https://curl.haxx.se/download/curl-7.78.0.tar.gz
      - tar -xzf curl-7.78.0.tar.gz
      - pushd curl-7.78.0 && ./configure --prefix=/usr/local --with-openssl && make && sudo make install && popd
      - wget https://archive.apache.org/dist/thrift/0.13.0/thrift-0.13.0.tar.gz
      - tar -xzf thrift-0.13.0.tar.gz
      - pushd thrift-0.13.0 && ./configure --prefix=/usr --with-php=no --with-erlang=no --with-go=no --with-java=no --with-python=no --with-py3=no --with-ruby=no --with-nodejs=no --with-c_glib=no --with-cpp=yes && make && sudo make install && popd
      script:
      - mkdir ${TRAVIS_BUILD_DIR}/build
      - cd ${TRAVIS_BUILD_DIR}/build
      - cmake -DCMAKE_INSTALL_PREFIX=/usr/local .. && make
    - name: Frontend
      language: node_js
      node_js:
      - 16
      before_script:
      - cd ${TRAVIS_BUILD_DIR}/frontend
      - cp src/utils/Config.default.js src/utils/Config.js
      - npm install
      script:
      - npm run build
    - name: StatusPage
      language: node_js
      node_js:
      - 16
      before_script:
      - cd ${TRAVIS_BUILD_DIR}/statuspage
      - cp src/utils/Config.default.js src/utils/Config.js
      - npm install
      script:
      - npm run build